CREATE TABLE `jg_material_brand` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `material_brand` varchar(50) DEFAULT NULL COMMENT '材料品牌',
  `material_category` varchar(50) DEFAULT NULL COMMENT '材料类别',
  `material_category_code` varchar(50) DEFAULT NULL COMMENT '材料类别code',
  `sample_photo` varchar(255) DEFAULT NULL COMMENT '样板照片',
  `sample_content` varchar(255) DEFAULT NULL COMMENT '样板内容',
  `material_approach_photo` varchar(255) DEFAULT NULL COMMENT '材料进场照片',
  `material_approach_content` varchar(255) DEFAULT NULL COMMENT '材料进场内容',
  `material_approach_quantity` varchar(255) DEFAULT NULL COMMENT '材料进场数量',
  `attachment` json DEFAULT NULL COMMENT '附件',
  `attachment1` json DEFAULT NULL COMMENT '附件1',
  `attachment2` json DEFAULT NULL COMMENT '附件2',
  `status` int(1) DEFAULT '0' COMMENT '状态 0 审批中 1 审批完成 2 驳回',
  `status1` int(1) DEFAULT '-1' COMMENT '状态 0 审批中 1 审批完成 2 驳回',
  `status2` int(1) DEFAULT '-1' COMMENT '状态 0 审批中 1 审批完成 2 驳回',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志（0代表存在 2代表删除）',
  `create_user_id` int(11) DEFAULT NULL COMMENT '创建者Id',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_user_id` int(11) DEFAULT NULL COMMENT '更新者Id',
  `update_time` datetime DEFAULT NULL COMMENT '最后更新时间',
  `project_id` int(11) DEFAULT NULL COMMENT '项目id',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1680524479681269761 DEFAULT CHARSET=utf8mb4 COMMENT='材料品牌'