GET {{host}}/web/api/v1/daily_report/detail/id?id=1
Authorization: {{Authorization}}

###
GET http://localhost:8088/web/api/v1/daily_report/detail/id?id=1670610421997899776
Authorization: {{Authorization}}

###
POST http://localhost:8088/web/api/v1/daily_report/addOrUpdate
Authorization: {{Authorization}}
Content-Type: application/json

{
  "content": "test_94a4ea761893",
  "reportPeople": "test_c47de31f0898"

}

###
POST http://localhost:8088/web/api/v1/daily_report/page
Authorization: {{Authorization}}
Content-Type: application/json

{
  "status": 0,
  "pageNum": 1,
  "pageSize": 5
}

###
GET http://localhost:8088/web/api/v1/daily_report/list
Authorization: {{Authorization}}