### 入库导入
POST {{host}}/warehousing/warehousing/import
Content-Type: multipart/form-data; boundary=----1

------1
Content-Disposition: form-data; name="file"; filename="/C:/Users/Dell/Desktop/出库明细.xlsx"
Content-Type: text/plain

< ./入库明细.xlsx
------1


### 出库导入
POST {{host}}/ql/outbound/import
Content-Type: multipart/form-data; boundary=----2

------2
Content-Disposition: form-data; name="file"; filename="/C:/Users/Dell/Desktop/出库明细.xlsx"
Content-Type: text/plain

< ./出库明细.xlsx
------2


### Send a form with the text and file fields
POST https://httpbin.org/post
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="element-name"
Content-Type: text/plain

Name
--WebAppBoundary
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ./request-form-data.json
--WebAppBoundary--


### 根据字典类型查询字典数据信息
GET {{host}}/system/dict/data/type/jg_project_type
Authorization: {{Authorization}}

###  新增or修改三级教育培训
POST {{host}}/web/api/v1/safetyDisclosure/educationTrain/addOrUpdate
Authorization: {{Authorization}}
Content-Type: application/json

{
  "content": "test_b8d8c750b17f",
  "trainer": "test_4e0514065c10",
  "fj": "test_23f0f500553a",
  "fjType": "test_7d0e73c37a21",
  "fjName": "test_c838652d6ae7",
  "projectId": 97,
  "trainDate": "2013-05-31 19:27:04",
  "createTime": "2020-08-15 14:28:17",
  "updateTime": "2031-09-12 18:22:31"
}

###  查询所有附件
GET {{host}}/web/api/v1/safetyDisclosure/educationTrain/fetchAll/97
Authorization: {{Authorization}}

###  删除附件
DELETE {{host}}/web/api/v1/safetyDisclosure/educationTrain/1
Authorization: {{Authorization}}