


@startuml
'https://plantuml.com/sequence-diagram

title 嘉兴铁投混凝土拌合站智控管理系统SSO登录时序图

嘉兴建管前端->嘉兴建管服务端: 调用加密接口，返回用户名&密码加密后的字符
嘉兴建管服务端->嘉兴建管前端: 用户名&密码加密后的字符
嘉兴建管前端->拌合站前端: a标签跳转，跳转的url中包含加密字符
拌合站前端->拌合站服务端: 后端解密
拌合站服务端->拌合站前端: 解密结果[成功：跳转首页，失败：前端提示异常信息]


@enduml