###
GET {{host}}/web/api/v1/construction_plan/detail/id?id=1
Authorization: {{Authorization}}

###
POST {{host}}/web/api/v1/construction_plan/addOrUpdate
Authorization: {{Authorization}}
Content-Type: application/json

{
  "content": "test_94a4ea761893",
  "reportPeople": "test_c47de31f0898"

}

###
POST {{host}}/web/api/v1/construction_plan/page
Authorization: {{Authorization}}
Content-Type: application/json

{
  "status": 0,
  "pageNum": 1,
  "projectId": 1,
  "pageSize": 5
}

###
GET {{host}}/web/api/v1/construction_plan/list
Authorization: {{Authorization}}